### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by BigDeepBlue** [no80dy/async-api-for-cinema#28]
Хорошая работа 👍 Далее несколько рекомендаций по доработке:
1. В docker-compose.yaml не нужно пробрасывать порты [ES](https://github.com/no80dy/async-api-for-cinema/blob/6022020bb5370cc0f3e74d1c530c045e1e7686b4/docker-compose.yml#L42) наружу. В части безопасности приложения это плохо.
2. В продакшене не рекомендуется запускать код через uvicorn напрямую, вот тут про это написано несколько слов https://www.uvicorn.org/deployment/#gunicorn.
3. А это тут точно нужно? Кажется в этом сервисе не используется postgres
https://github.com/no80dy/async-api-for-cinema/blob/6022020bb5370cc0f3e74d1c530c045e1e7686b4/src/entrypoint.sh#L3-L7
4. Конфиг `src/core/config.py` можно было оформить в виде класса:
    ```python
    from pydantic import BaseSettings
    
    class Settings(BaseSettings):
        redis_host: str = Field(..., env='REDIS_HOST')
        class Config:
            env_file = '.env'
    
    settings = Settings()
    ```
    и затем использовать инстанс конфига setting в разных частях приложения. Плюс такого подхода в том, что происходит валидация типов переменных окружения при помощи pydantic. Также при создании инфраструктуры под тесты, можно будет наследоваться от этого класса и создать отдельный тестовый конфиг со своими переменными окружения. Подробнее https://pydantic-docs.helpmanual.io/usage/settings/
      
      Еще пример:
      ```python
      class Settings(BaseSettings):
          project_name: str = 'Some project name'
          redis_host: str = ...
          redis_port: int = ...
          elastic_host: str = Field(..., env='ELASTIC_HOST_NAME')
          elastic_port: int = Field(9200, env='ELASTIC_PORT')
      ```
      
      BaseSettings регистронезависимый и работает вот так:
            - присвоит в поле project_name значение переменной PROJECT_NAME, а если ее нет, то даст значение по умолчанию 'Some project name'
            - redis_host мы сделали обязательным полем (... - служебный символ), если не будет переменной окружения REDIS_HOST, то проект не заведется
            - elastic_host мы сделали обязательным и явно указали имя переменной окружения, т.к. она отличается от имени поля
            - elastic_port так же как и с хостом, но указали и значение по умолчанию
5. Начиная с python 3.10 можно не использовать Optional из модуля typing. В номов синтаксисе можно использовать вот такую конструкцию:  `redis: Redis | None = None`
6. С версии python 3.9 для стандартных коллекций больше не нужен модуль typing: https://docs.python.org/3.9/whatsnew/3.9.html#type-hinting-generics-in-standard-collections.
7. Учитывая два пункты выше [вот тут](https://github.com/no80dy/async-api-for-cinema/blob/6022020bb5370cc0f3e74d1c530c045e1e7686b4/src/models/film.py#L32-L43) можно сделать вот так:
      ```python
      class Film(FilmShort):
          title: str
          imdb_rating: float | None
          description: str | None
          genres: list[Genres]
          actors: list[IdName] | None
          writers: list[IdName] | None
          directors: list[IdName] | None
      ```
8. Параметры пагинации в эндпоинтах необходимо дооформить в части описания для Swagger и их необходимо валидировать, например, так. 
      ```python
      page_size: Annotated[int, Query(description='Pagination page size', ge=1)] = 10,
      ```
      https://fastapi.tiangolo.com/tutorial/query-params-str-validations/#import-query-and-annotated
      Про валидацию посмотрите тут https://fastapi.tiangolo.com/tutorial/path-params-numeric-validations/#number-validations-greater-than-or-equal это применимо и к Query 
9. Текстовые сообщения, отдаваемые пользователю, (film not found) у вас расположены в разных местах кода, если появится задача добавить информативности или изменить текст сообщения, или встанет вопрос про мультиязычность, то придется по всему проекту выискивать и менять. Будет проще справиться с этой задачей, если такие сообщения будут вынесены в отдельное место в виде констант (например).

**Comment by Ruslan964** [comment]
предлагаю уточнить у ревьювера как должны тогда перекачку данных через etl осуществить

1. прокидывание портов нужно только для разовой перекачки данных в эластик, т.к. етл тащить в данный проект не нужно согласо ТЗ, то мы его поставили рядом идоступа к внутренней сети, без открытия портов невозможно

**Comment by Ruslan964** [comment]
предлагаю уточнить у ревьювера как должны тогда перекачку данных через etl осуществить

1. прокидывание портов нужно только для разовой перекачки данных в эластик, т.к. етл тащить в данный проект не нужно согласо ТЗ, то мы его поставили рядом идоступа к внутренней сети, без открытия портов невозможно

**Comment by Ruslan964** [comment]
2. не понял про "использовать напрямую" - что значит? это он про блок if __name__ == "__main__" или про CMD...?

**Comment by no80dy** [comment]
> 2. не понял про "использовать напрямую" - что значит? это он про блок if **name** == "**main**" или про CMD...?

Это он про CMD. `Gunicorn` должен запускать `uvicorn` воркеры, как я понял

**Comment by no80dy** [comment]
> предлагаю уточнить у ревьювера как должны тогда перекачку данных через etl осуществить
> 
> 1. прокидывание портов нужно только для разовой перекачки данных в эластик, т.к. етл тащить в данный проект не нужно согласо ТЗ, то мы его поставили рядом идоступа к внутренней сети, без открытия портов невозможно

Мы, как я понял, потащили ETL в `docker compose` только для того, чтобы нам удобно было разрабатывать

На продакшн это будут два отдельных микросервиса, которые будут оркетрироваться, например, с помощью k8s и общаться с помощью его внутренней сети. ETL в такой среде будет постоянно заниматься перекачкой всех моделей

Предлагаю, как вариант, создать `production docker compose`, убрать оттуда ETL и закрыть порт у elasticsearch

**Comment by Ruslan964** [comment]
> > 2. не понял про "использовать напрямую" - что значит? это он про блок if **name** == "**main**" или про CMD...?
> 
> Это он про CMD. `Gunicorn` должен запускать `uvicorn` воркеры, как я понял

есть понимание как это пофиксить?
прочитал статью по ссылке - нифига не понял :)

попробовал решить "в лоб", не получилось 
![image](https://github.com/no80dy/async-api-for-cinema/assets/65903274/10300558-9b55-45ff-a7d8-f03adc3a6b0e)


если ни у кого понимания нет как решается, то позже еще поизучаю, если есть понимание что от нас требуется пофиксить по данному пункту, просьба рассказать)

**Comment by Ruslan964** [comment]
> > предлагаю уточнить у ревьювера как должны тогда перекачку данных через etl осуществить
> > 
> > 1. прокидывание портов нужно только для разовой перекачки данных в эластик, т.к. етл тащить в данный проект не нужно согласо ТЗ, то мы его поставили рядом идоступа к внутренней сети, без открытия портов невозможно
> 
> Мы, как я понял, потащили ETL в `docker compose` только для того, чтобы нам удобно было разрабатывать
> 
> На продакшн это будут два отдельных микросервиса (у каждого будет отдельный репо), которые будут оркетрироваться, например, с помощью k8s и общаться с помощью его внутренней сети. ETL в такой среде будет постоянно заниматься перекачкой всех моделей
> 
> Предлагаю, как вариант, создать `production docker compose`, убрать оттуда ETL и закрыть порт у elasticsearch

да, давай тогда я сделаю отдельный компоуз файд, из него удалю вообще весь ЕТЛ, будем думать будто в эластике всегда есть данные и их туда качает отдельный сервис.

только тут вопрос, который хотелось бы задать ревьюверу - у нас другой сервис подключится к сети, который создает наш компоуз? чтобы доступ от внешнего сервиса был к эластику.. Задашь этот вопрос ревьюверу?)

**Comment by Ruslan964** [comment]
3. это сделано больше для того, чтобы в рамках разработки мы дождались БД (как раз этот скрипт) и потом ждем пока БД перекинет данные в эластик (sleep 10 секунд). Если исходим, что ЕТЛ внешний сервис делает, то да, удаляю этот файл и из dockerfile тоже соответственно удаляю вызов файла :)

**Comment by Ruslan964** [comment]
замечания 5,6,7 - это замечания про одно и то же, замечания считаю для галочки, но объемное для исправления... можно, конечно, все поправить, но это тупая монотонная работа, можно прикинуться дурачками и сказать, что мы разрабатываем на версии 3.7 - там без typing не обойтись и поэтому так использовали :)

по какому пути пойдем?)

**Comment by Ruslan964** [comment]
9. пофиксил

**Comment by no80dy** [comment]
> > > 2. не понял про "использовать напрямую" - что значит? это он про блок if **name** == "**main**" или про CMD...?
> > 
> > 
> > Это он про CMD. `Gunicorn` должен запускать `uvicorn` воркеры, как я понял
> 
> есть понимание как это пофиксить? прочитал статью по ссылке - нифига не понял :)
> 
> попробовал решить "в лоб", не получилось ![image](https://user-images.githubusercontent.com/65903274/278616733-10300558-9b55-45ff-a7d8-f03adc3a6b0e.png)
> 
> если ни у кого понимания нет как решается, то позже еще поизучаю, если есть понимание что от нас требуется пофиксить по данному пункту, просьба рассказать)

Скорее всего эта проблема связана с тем, что `gunicorn` нужно установить в `pip`.
Еще я нашел репо с деплоем FastAPI на `gunicorn`:
[fastapi-nginx-gunicorn](https://github.com/dylanjcastillo/fastapi-nginx-gunicorn)

**Comment by no80dy** [comment]
> замечания 5,6,7 - это замечания про одно и то же, замечания считаю для галочки, но объемное для исправления... можно, конечно, все поправить, но это тупая монотонная работа, можно прикинуться дурачками и сказать, что мы разрабатываем на версии 3.7 - там без typing не обойтись и поэтому так использовали :)
> 
> по какому пути пойдем?)

Согласен, но я лучше перед отправкой поправлю это дело, на всякий случай)
Можно будет обсудить все эти стандарты на следующем созвоне

**Comment by Ruslan964** [comment]
> > > > 2. не понял про "использовать напрямую" - что значит? это он про блок if **name** == "**main**" или про CMD...?
> > > 
> > > 
> > > Это он про CMD. `Gunicorn` должен запускать `uvicorn` воркеры, как я понял
> > 
> > 
> > есть понимание как это пофиксить? прочитал статью по ссылке - нифига не понял :)
> > попробовал решить "в лоб", не получилось ![image](https://user-images.githubusercontent.com/65903274/278616733-10300558-9b55-45ff-a7d8-f03adc3a6b0e.png)
> > если ни у кого понимания нет как решается, то позже еще поизучаю, если есть понимание что от нас требуется пофиксить по данному пункту, просьба рассказать)
> 
> Скорее всего эта проблема связана с тем, что `gunicorn` нужно установить в `pip`. Еще я нашел репо с деплоем FastAPI на `gunicorn`: [fastapi-nginx-gunicorn](https://github.com/dylanjcastillo/fastapi-nginx-gunicorn)

пофиксил проблему №2.
Иногда полезно читать официальную доку))))) решение взял там: https://fastapi.tiangolo.com/ru/deployment/server-workers/#:~:text=in%20that%20chapter.-,Gunicorn%20with%20Uvicorn%20Workers,-%C2%B6

**Comment by BigDeepBlue** [comment]
> предлагаю уточнить у ревьювера как должны тогда перекачку данных через etl осуществить
> 
> 1. прокидывание портов нужно только для разовой перекачки данных в эластик, т.к. етл тащить в данный проект не нужно согласо ТЗ, то мы его поставили рядом идоступа к внутренней сети, без открытия портов невозможно

Для этого обычно делают 2 файла docker-compose.yaml и docker-compose.dev.yaml  и во втором все для комфортной разработки. А первый готов для отправки в боевое окружение. Или же docker-compose.override.yml  https://devilbox.readthedocs.io/en/latest/configuration-files/docker-compose-override-yml.html#docker-compose-override-yml-1

**Comment by BigDeepBlue** [comment]
> замечания 5,6,7 - это замечания про одно и то же, замечания считаю для галочки, но объемное для исправления... можно, конечно, все поправить, но это тупая монотонная работа, можно прикинуться дурачками и сказать, что мы разрабатываем на версии 3.7 - там без typing не обойтись и поэтому так использовали :)
> 
> по какому пути пойдем?)

Это была рекомендация. Новый проект начинать на старой версии python (это я про 3.7) - такое себе решение. А использовать 3.10+ и не пользоваться всеми полезностями нового синтаксиса, тоже странно.

**Comment by BigDeepBlue** [comment]
LGTM
