### ISSUE TITLE
Настроить докерфайл и докеркомпоуз

### ISSUE THREAD

**Issue by no80dy** [no80dy/async-api-for-cinema#3]
Нужен Dockerfile для билда бекенда для API. Также нужно создать (или адаптировать созданные ранее) docker-compose, чтобы поднимались все сервисы разом.

Оценка: 5

**Comment by Ruslan964** [comment]
было сделано в нескольких ПРах по частям. последний фикс на текущий момент вот тут: https://github.com/no80dy/async-api-for-cinema/pull/14
