### ISSUE TITLE
Создать модели для фильмов и связанных данных

### ISSUE THREAD

**Issue by no80dy** [no80dy/async-api-for-cinema#4]
Создать модели, прописав правильные типы данных для:

фильмов,
жанров,
актеров, сценаристов, режиссеров.
Оценка: 5

**Comment by Ruslan964** [comment]
если здесь я правильно понял задачу, то нужно было описать модели pydantic, это сделано вот тут: https://github.com/no80dy/async-api-for-cinema/pull/15
